spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/${DEV_DATABASE_URL}
    username: ${DEV_DATABASE_USER}
    password: ${DEV_DATABASE_PASSWORD}

logging:
  level:
    hr.adriaticanimation.saf-planner: DEBUG
