spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/${PROD_DATABASE_URL}
    username: ${PROD_DATABASE_USER}
    password: ${PROD_DATABASE_PASSWORD}

security:
  jwt:
    secret-key: ${PROD_JWT_SECRET_KEY}

logging:
  level:
    hr.adriaticanimation.saf-planner: INFO
