spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/${DEV_DATABASE_URL}
    username: ${DEV_DATABASE_USER}
    password: ${DEV_DATABASE_PASSWORD}

security:
  jwt:
    secret-key: ${DEV_JWT_SECRET_KEY}

logging:
  level:
    hr.adriaticanimation.saf-planner: DEBUG
