server:
  port: 8080

spring:
  application:
    name: saf-planner
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  flyway:
    enabled: true

logging:
  level:
    hr.adriaticanimation.saf-planner: DEBUG
