server:
  port: 8080

spring:
  application:
    name: saf-planner
  config:
    import: file:.env[.properties]
  flyway:
    enabled: true
  profiles:
    active: dev

springdoc:
  swagger-ui:
    path: /api-docs
