server:
  port: 8080

spring:
  application:
    name: saf-planner
  flyway:
    enabled: true
  profiles:
    active: dev

security:
  jwt:
    expiration-time: 900000
  refresh-token:
    expiration-time: 604800000
    renewal: 86400000

springdoc:
  swagger-ui:
    path: /api-docs
