spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/${PROD_DATABASE_URL}
    username: ${PROD_DATABASE_USER}
    password: ${PROD_DATABASE_PASSWORD}

logging:
  level:
    hr.adriaticanimation.saf-planner: INFO
