spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres

uploads:
  directory: ${user.home}/saf-planner/uploads

logging:
  level:
    hr.adriaticanimation.saf-planner: DEBUG
