###
POST http://localhost:8080/api/auth/sign-up
Content-Type: application/json

{
  "email": "user2@email.com",
  "firstName": "George",
  "lastName": "Bush",
  "password": "user2Password"
}
> {% client.global.set("jwt", JSON.parse(JSON.stringify(response.body)).jwt);%}

###
POST http://localhost:8080/api/auth/sign-in
Content-Type: application/json

{
  "email": "user2@email.com",
  "password": "user2Password"
}
> {% client.global.set("jwt", JSON.parse(JSON.stringify(response.body)).jwt);%}

###
POST http://localhost:8080/api/auth/sign-out
Authorization: Bearer {{jwt}}}

###
POST http://localhost:8080/api/auth/refresh-token