###
POST http://localhost:8080/api/comments
Content-Type: application/json

{
    "fragmentId": 80,
    "content": "I really like how the long description has been updated here. Good job!"
}

###
PUT http://localhost:8080/api/comments
Content-Type: application/json

{
    "commentId": 1,
    "content": ""
}

###
DELETE http://localhost:8080/api/comments?id=2