###
GET http://localhost:8080/api/fragments?projectId=4

###
POST http://localhost:8080/api/fragments
Content-Type: application/json

{
  "shortDescription": "Test fragment - deleting image with it",
  "longDescription": "Test long description",
  "durationInSeconds": 5,
  "onTimeline": true,
  "position": 1,
  "projectId": 4
}

###
PATCH http://localhost:8080/api/fragments?id=80
Content-Type: application/json

{
    "shortDescription": "Updated short description"
}

###
PATCH http://localhost:8080/api/fragments?id=80
Content-Type: application/json

{
    "longDescription": "Updated long description"
}

###
PATCH http://localhost:8080/api/fragments?id=80
Content-Type: application/json

{
    "durationInSeconds": 10
}

###
PATCH http://localhost:8080/api/fragments?id=80
Content-Type: application/json

{
    "onTimeline": false
}

###
PATCH http://localhost:8080/api/fragments?id=80
Content-Type: application/json

{
    "position": 1
}

###
DELETE http://localhost:8080/api/fragments?id=93
Content-Type: application/json
