###
GET http://localhost:8080/api/label?projectId=1

###
POST http://localhost:8080/api/label
Content-Type: application/json

{
    "projectId": 1,
    "description": "Test",
    "color": "#6cd36d"
}

###
POST http://localhost:8080/api/label/fragment
Content-Type: application/json

{
    "labelId": 4,
    "fragmentId": 1
}

###
POST http://localhost:8080/api/label/fragment/all
Content-Type: application/json

{
    "labelIds": [20, 21, 34],
    "fragmentId": 58
}

###
PUT http://localhost:8080/api/label
Content-Type: application/json

{
    "labelId": 5,
    "description": "Test label",
    "color": "#666666"
}

###
DELETE http://localhost:8080/api/label
Content-Type: application/json

{
    "labelId": 4
}

###
DELETE http://localhost:8080/api/label/fragment
Content-Type: application/json

{
    "labelId": 4,
    "fragmentId": 1
}