###
GET http://localhost:8080/api/label?projectId=1

###
POST http://localhost:8080/api/label
Content-Type: application/json

{
    "projectId": 1,
    "description": "Test",
    "color": "#6cd36d"
}

###
POST http://localhost:8080/api/label/fragment
Content-Type: application/json

{
    "labelId": 4,
    "fragmentId": 1
}

###
PUT http://localhost:8080/api/label/color
Content-Type: application/json

{
    "labelId": 4,
    "color": "#000000"
}

###
PUT http://localhost:8080/api/label/desription
Content-Type: application/json

{
    "labelId": 4,
    "description": "Test label"
}

###
DELETE http://localhost:8080/api/label
Content-Type: application/json

{
    "labelId": 4
}

###
DELETE http://localhost:8080/api/label/fragment
Content-Type: application/json

{
    "labelId": 4,
    "fragmentId": 1
}