###
GET http://localhost:8080/api/labels?projectId=4

###
POST http://localhost:8080/api/label
Content-Type: application/json

{
    "projectId": 4,
    "description": "Test",
    "color": "#6cd36d"
}

###
POST http://localhost:8080/api/fragment/label
Content-Type: application/json

{
    "labelId": 39,
    "fragmentId": 80
}

###
POST http://localhost:8080/api/fragment/labels
Content-Type: application/json

{
    "labelIds": [39],
    "fragmentId": 58
}

###
PUT http://localhost:8080/api/label?id=39
Content-Type: application/json

{
    "description": "Test label",
    "color": "#666666"
}

###
DELETE http://localhost:8080/api/label?id=39
Content-Type: application/json

###
DELETE http://localhost:8080/api/fragment/label?labelId=39&fragmentId=58
Content-Type: application/json