###
GET http://localhost:8080/api/project/all

###
GET http://localhost:8080/api/project?projectId=3

###
POST http://localhost:8080/api/project
Content-Type: application/json

{
    "title": "Test project",
    "description": "Test project for user 2",
    "estimatedLengthInSeconds": 300
}

###
PUT http://localhost:8080/api/project/title
Content-Type: application/json

{
    "projectId": 14,
    "title": "Blaa 2"
}

###
PUT http://localhost:8080/api/project/description
Content-Type: application/json

{
    "projectId": 14,
    "description": "Description"
}

###
PUT http://localhost:8080/api/project/estimated-length
Content-Type: application/json

{
    "projectId": 14,
    "estimatedLengthInSeconds": 182
}

###
DELETE http://localhost:8080/api/project
Content-Type: application/json

{
    "projectId": 2
}