###
GET http://localhost:8080/api/project

###
POST http://localhost:8080/api/project
Content-Type: application/json

{
    "title": "My second project",
    "description": "This is a project made for testing out the server implementation - mostly for ordering",
    "estimatedLengthInSeconds": 360
}

###
PUT http://localhost:8080/api/project/title
Content-Type: application/json

{
    "projectId": 14,
    "title": "Blaa 2"
}

###
PUT http://localhost:8080/api/project/description
Content-Type: application/json

{
    "projectId": 14,
    "description": "Description"
}

###
PUT http://localhost:8080/api/project/estimated-length
Content-Type: application/json

{
    "projectId": 14,
    "estimatedLengthInSeconds": 182
}

###
DELETE http://localhost:8080/api/project
Content-Type: application/json

{
    "projectId": 2
}