###
GET http://localhost:8080/api/screenplays?projectId=3

###
POST http://localhost:8080/api/screenplays
Content-Type: application/json

{
    "projectId": 4,
    "content": {"id": 1, "type": "screenplay", "children": [{"type": "header", "children": [{"text": "fade in:"}]}, {"type": "action", "children": [{"text": "Action sequence"}]}]}
}

###
PUT http://localhost:8080/api/screenplays
Content-Type: application/json

{
    "id": 1,
    "content": {"id": 1, "type": "screenplay", "children": [{"type": "header", "children": [{"text": "fade in:"}]}, {"type": "action", "children": [{"text": "New action sequence"}]}]}
}

###
DELETE http://localhost:8080/api/screenplays?id=1

###
POST http://localhost:8080/api/screenplays/export
Content-Type: application/json

{
    "id": 5,
    "title": "Title of My Film",
    "author": "Mahatma Gandhi",
    "email": "mahatma.gandhi@email.com",
    "phoneNumber": "+372 5123456",
    "date": "21. November 2004"
}