###
GET localhost:8080/api/projects/shared

###
GET localhost:8080/api/projects/shared?projectId=4

###
GET localhost:8080/api/projects/shared/fragments?projectId=4

###
POST localhost:8080/api/projects/shared
Content-Type: application/json

{
    "projectId": 4,
    "shareWithId": 1
}

###
DELETE localhost:8080/api/projects/shared?projectId=4&userId=1